In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [76]:
#Se guarda el dataset en una variable (df_meta) y mostramos las 5 primeras filas y todas sus columnas.
df_meta = pd.read_csv('REPORTE-XPLORA-MAYO-2024-AGOSTO-2025.csv')
pd.set_option('display.max_columns', None)
df_meta.head(10)

,Nombre de la campaña,Identificador de la campaña,Nombre del conjunto de anuncios,Identificador del conjunto de anuncios,Nombre del anuncio,Identificador del anuncio,Mes,Objetivo,Edad,Sexo,Llamada a la acción,Tipo de resultado,Resultados,Importe gastado (COP),Alcance,Impresiones,Costo por resultado,Clics en el enlace,CPC (costo por clic en el enlace),CPM (costo por mil impresiones),CTR (todos),Conversaciones con mensajes iniciadas,Frecuencia,Inicio del informe,Fin del informe
0,Xiudad | MAYO | INTERACCIÓN - 13 MAYO 2024,120208939348690362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209021784370362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209056012500362,2024-05-03 - 2024-05-31,OUTCOME_ENGAGEMENT,55-64,male,WHATSAPP_MESSAGE,NaN,NaN,26,NaN,6,NaN,NaN,NaN,4333.333333,0.000000,NaN,NaN,2024-05-03,2024-05-31
1,Xiudad | MAYO | INTERACCIÓN - 13 MAYO 2024,120208939348690362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209021784370362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209056012500362,2024-06-01 - 2024-06-30,OUTCOME_ENGAGEMENT,35-44,male,WHATSAPP_MESSAGE,NaN,NaN,9581,NaN,794,NaN,5.0,1916.200000,12066.750630,1.763224,NaN,NaN,2024-06-01,2024-06-30
2,Xiudad | MAYO | INTERACCIÓN - 13 MAYO 2024,120208939348690362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209021784370362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209056012500362,2024-05-03 - 2024-05-31,OUTCOME_ENGAGEMENT,25-34,male,WHATSAPP_MESSAGE,NaN,NaN,935,NaN,86,NaN,1.0,935.000000,10872.093023,1.162791,NaN,NaN,2024-05-03,2024-05-31
3,Xiudad | MAYO | INTERACCIÓN - 13 MAYO 2024,120208939348690362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209021784370362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209056012500362,2024-05-03 - 2024-05-31,OUTCOME_ENGAGEMENT,35-44,male,WHATSAPP_MESSAGE,NaN,NaN,983,NaN,71,NaN,2.0,491.500000,13845.070423,5.633803,NaN,NaN,2024-05-03,2024-05-31
4,Xiudad | MAYO | INTERACCIÓN - 13 MAYO 2024,120208939348690362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209021784370362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209056012500362,2024-05-03 - 2024-05-31,OUTCOME_ENGAGEMENT,45-54,male,WHATSAPP_MESSAGE,NaN,NaN,866,NaN,42,NaN,2.0,433.000000,20619.047619,7.142857,NaN,NaN,2024-05-03,2024-05-31
5,Xiudad | MAYO | INTERACCIÓN - 13 MAYO 2024,120208939348690362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209021784370362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209056012500362,2024-05-03 - 2024-05-31,OUTCOME_ENGAGEMENT,35-44,female,WHATSAPP_MESSAGE,NaN,NaN,597,NaN,56,NaN,2.0,298.500000,10660.714286,5.357143,NaN,NaN,2024-05-03,2024-05-31
6,Xiudad | MAYO | INTERACCIÓN - 13 MAYO 2024,120208939348690362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209021784370362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209056012500362,2024-05-03 - 2024-05-31,OUTCOME_ENGAGEMENT,25-34,female,WHATSAPP_MESSAGE,NaN,NaN,472,NaN,67,NaN,1.0,472.000000,7044.776119,2.985075,NaN,NaN,2024-05-03,2024-05-31
7,Xiudad | MAYO | INTERACCIÓN - 13 MAYO 2024,120208939348690362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209021784370362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209056012500362,2024-05-03 - 2024-05-31,OUTCOME_ENGAGEMENT,45-54,female,WHATSAPP_MESSAGE,NaN,NaN,890,NaN,55,NaN,1.0,890.000000,16181.818182,5.454545,NaN,NaN,2024-05-03,2024-05-31
8,Xiudad | MAYO | INTERACCIÓN - 13 MAYO 2024,120208939348690362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209021784370362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209056012500362,2024-05-03 - 2024-05-31,OUTCOME_ENGAGEMENT,25-34,unknown,WHATSAPP_MESSAGE,NaN,NaN,138,NaN,5,NaN,NaN,NaN,27600.000000,0.000000,NaN,NaN,2024-05-03,2024-05-31
9,Xiudad | MAYO | INTERACCIÓN - 13 MAYO 2024,120208939348690362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209021784370362,Xiudad | MAYO | INTERACCIÓN - PIEZA,120209056012500362,2024-06-01 - 2024-06-30,OUTCOME_ENGAGEMENT,45-54,male,WHATSAPP_MESSAGE,NaN,NaN,7489,NaN,548,NaN,6.0,1248.166667,13666.058394,2.007299,NaN,NaN,2024-06-01,2024-06-30

In [71]:
#Se observa cuántas filas y columans tiene el dataset.
df_meta.shape

(2220, 25)

In [73]:
#Se observa información básica sobre cada columna como índice, nombre, cantidad de no nulos, tipo de dato
df_meta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2220 entries, 0 to 2219
Data columns (total 25 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Nombre de la campaña                    2220 non-null   object
 1   Identificador de la campaña             2220 non-null   int64
 2   Nombre del conjunto de anuncios         2220 non-null   object
 3   Identificador del conjunto de anuncios  2220 non-null   int64
 4   Nombre del anuncio                      2220 non-null   object
 5   Identificador del anuncio               2220 non-null   int64
 6   Mes                                     2220 non-null   object
 7   Objetivo                                2220 non-null   object
 8   Edad                                    2220 non-null   object
 9   Sexo                                    2220 non-null   object
 10  Llamada a la acción                     2220 non-null   object
 11  Tipo de resultado                       945 non-null    object
 12  Resultados                              945 non-null    float64
 13  Importe gastado (COP)                   2220 non-null   int64
 14  Alcance                                 0 non-null      float64
 15  Impresiones                             2220 non-null   int64
 16  Costo por resultado                     945 non-null    float64
 17  Clics en el enlace                      1610 non-null   float64
 18  CPC (costo por clic en el enlace)       1610 non-null   float64
 19  CPM (costo por mil impresiones)         2218 non-null   float64
 20  CTR (todos)                             2218 non-null   float64
 21  Conversaciones con mensajes iniciadas   0 non-null      float64
 22  Frecuencia                              0 non-null      float64
 23  Inicio del informe                      2220 non-null   object
 24  Fin del informe                         2220 non-null   object
dtypes: float64(9), int64(5), object(11)
memory usage: 433.7+ KB

### DICCIONARIO DE DATOS
0. Nombre de la campaña: Nombre asignado a la campaña en Meta , (Tipo de variable = Categórica )
1. Identificador de la campaña: ID único de la campaña, (Tipo de variable = Númerica)
2. Nombre del conjunto de anuncios: Nombre asignado al conjunto de anuncios de la campaña en Meta Ads, (Tipo de variable = Categórica)
3. Identificador del conjunto de anuncios: ID único del conjunto de anuncios, (Tipo de variable = Númerica)
4. Nombre del anuncio: Nombre asignado al anuncio en el conjunto de anuncios en Meta Ads, (Tipo de variable = Categórica)
5. Identificador del anuncio: ID único del anuncio, (Tipo de variable = Númerica)
6. Mes: Período de duración del conjunto de anuncios/anuncio, (Tipo de variable = Categórica)
7. Objetivo: Objetivo de la campaña (ventas, clientes potenciales, mensajes, etc), (Tipo de variable = Categórica)
8. Edad: Rango de edades con las cuales se segmentó el conjunto de anuncios, (Tipo de variable = Categórica)
9. Sexo: Segmento de género para cada conjunto de anuncios, (Tipo de variable = Categórica)
10. Llamada a la acción: Botón usado para motivar al usuario a realizar una acción, (Tipo de variable = Categórica)
11. Tipo de resultado: Tipo de conversión medida, (Tipo de variable = Categórica)
12. Resultados: Cantidad de conversiones logradas, (Tipo de variable = Númerica)
13. Importe gastado (COP): Monto invertido en campaña/conjunto de anuncios/anuncios, (Tipo de variable = Númerica)
14. Alcance: Personas únicas alcanzadas, (Tipo de variable = Númerica)
15. Impresiones: Número total de veces que se mostró un anuncio, (Tipo de variable = Númerica)
16. Costo por resultado: Costo promedio por conversión, (Tipo de variable = Númerica)
17. Clics en el enlace: Número de clic en el anuncio, (Tipo de variable = Númerica)
18. CPC (costo por clic en el enlace):Costo promedio por clic, (Tipo de variable = Númerica)
19. CPM (costo por mil impresiones): Costo promedio por mil impresiones, (Tipo de variable = Númerica)
20. CTR (todos): Porcentaje de clics sobre impresiones, (Tipo de variable = Númerica)
21. Conversaciones con mensajes iniciadas: Conversaciones de Whatsapp iniciadas, (Tipo de variable = Númerica)
22. Frecuencia: Promedio de veces que una persona vio el anuncio, (Tipo de variable = Númerica)
23. Inicio del informe: Fecha inicial del reporte, (Tipo de variable = Categórica)
24. Fin del informe: Fecha final del reporte, (Tipo de variable = Categórica)

In [78]:
# Conocer cantidad de nulos por columna
df_meta.isnull().sum()

Nombre de la campaña                         0
Identificador de la campaña                  0
Nombre del conjunto de anuncios              0
Identificador del conjunto de anuncios       0
Nombre del anuncio                           0
Identificador del anuncio                    0
Mes                                          0
Objetivo                                     0
Edad                                         0
Sexo                                         0
Llamada a la acción                          0
Tipo de resultado                         1275
Resultados                                1275
Importe gastado (COP)                        0
Alcance                                   2220
Impresiones                                  0
Costo por resultado                       1275
Clics en el enlace                         610
CPC (costo por clic en el enlace)          610
CPM (costo por mil impresiones)              2
CTR (todos)                                  2
Conversaciones con mensajes iniciadas     2220
Frecuencia                                2220
Inicio del informe                           0
Fin del informe                              0
dtype: int64